# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

alias python=/usr/local/bin/python3.7
alias python=/usr/bin/python3.7

source /Users/milostepavac/Documents/Software/Git/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

## Git
alias gs='git status'
alias ga='git add $*'
alias gc='git commit -m $*'
alias gtree='git log --oneline --decorate --all --graph'
alias gl='git log --pretty=format:"%%h %%an: %%s" --graph'
alias glog='git log --graph --pretty=format:"%%Cred%%h%%Creset %%C(bold yellow)%%d%%Creset %%C(bold blue)<%%an>%%Creset %%C(bold green)(%%cr)%%Creset - %%s" --abbrev-commit --date=relative'
alias gcf='git diff-tree --no-commit-id --name-only -r $*'
alias gshow='git show --stat --oneline HEAD'
alias gd='git diff'
alias gp='git pull'
alias grb='git branch -m $*'
alias gnb='git checkout -b $*'
alias gch='git shortlog -s -n --all'
alias gcm='git checkout master'
alias gcd='git checkout development'
alias gpo='git push -u origin $*'
alias gsa='git stash apply'
alias gst='git stash'
alias gpo='git push -u origin $*'

## AWS
alias awsp='export AWS_PROFILE=$*'